import{S as f,a,A as m}from"./assets/vendor-B-YS3wxx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const c=new f(".swiper",{navigation:{nextEl:".swiper-button-n",prevEl:".swiper-button-p"},pagination:{el:".swiper-pagination"},spaceBetween:10,reachBeginning:".swiper-button-p",reachEnd:".swiper-button-n",keyboard:{enabled:!0,onlyInViewport:!0},autoHeight:!0,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}}});c.on("reachEnd",function(){let e=document.querySelector(".swiper-button-n");e.style.border="1px solid #e4e5e6",e.style.pointerEvents="none";let t=document.querySelector(".btn-icon-n");t.style.stroke="#e4e5e6"});c.on("reachBeginning",function(){let e=document.querySelector(".swiper-button-p");e.style.border="1px solid #e4e5e6",e.style.pointerEvents="none";let t=document.querySelector(".btn-icon-p");t.style.stroke="#e4e5e6"});c.on("fromEdge",function(){let e=document.querySelector(".swiper-button-n");e.style.display="flex",e.style.border="1px solid #292929",e.style.pointerEvents="auto";let t=document.querySelector(".btn-icon-n");t.style.stroke="#292929";let n=document.querySelector(".swiper-button-p");n.style.display="flex",n.style.border="1px solid #292929",n.style.pointerEvents="auto";let s=document.querySelector(".btn-icon-p");s.style.stroke="#292929"});const w=document.querySelector(".review-list");fetch("https://portfolio-js.b.goit.study/api/reviews").then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{const t=e.map(n=>`
  <li class="review-list-order swiper-slide" id = "id_${n._id}">
  <div class="list-order-container">          
  <p class="review-list-text">${n.review}</p>
            <div class="review-list-box">
            <img class="review-list-img" src="${n.avatar_url}" alt="${n.author}">
                <p class="review-list-header">${n.author}</p>
                </div>
            </div>
        </li>`).join("");w.insertAdjacentHTML("beforeend",t)}).catch(e=>console.log(e));document.getElementById("contactForm").addEventListener("submit",async function(e){var o,r;e.preventDefault(),a.defaults.baseURL="https://portfolio-js.b.goit.study/api";const t=e.target,n=t.email.value.trim(),s=t.message.value.trim();if(!n||!s){d("Please fill in all the fields.");return}try{const i=await a.post("/requests",{email:n,message:s})}catch(i){console.error("Помилка:",i);const l=((r=(o=i.response)==null?void 0:o.data)==null?void 0:r.message)||"An unexpected error occurred. Please try again.";d(l)}});function d(e){alert(e)}document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".load-more"),t=document.querySelectorAll(".project-item[hidden]"),n=document.querySelector(".project-item:not([hidden])");let s=0;const o=3;e.addEventListener("click",()=>{for(let r=s;r<s+o&&r<t.length;r++)t[r].removeAttribute("hidden");if(s+=o,n){const r=n.getBoundingClientRect().height;window.scrollBy({left:0,top:r,behavior:"smooth"})}e.blur(),s>=t.length&&(e.style.display="none")})});document.addEventListener("DOMContentLoaded",()=>{new m("#faqAccordion",{duration:300,showMultiple:!1,collapseOthers:!0,openOnInit:[0]});const e=document.querySelectorAll(".faq-item");e.forEach((t,n)=>{t.querySelector(".faq-question").addEventListener("click",()=>{e.forEach((l,b)=>{const u=l.querySelector(".icon-arrow-top"),p=l.querySelector(".icon-arrow-bottom"),y=l.querySelector(".faq-answer");l!==t&&(l.classList.remove("active"),u.style.display="none",p.style.display="inline-block",y.style.display="none")});const o=t.querySelector(".icon-arrow-top"),r=t.querySelector(".icon-arrow-bottom"),i=t.querySelector(".faq-answer");t.classList.contains("active")?(t.classList.remove("active"),o.style.display="none",r.style.display="inline-block",i.style.display="none"):(t.classList.add("active"),o.style.display="inline-block",r.style.display="none",i.style.display="block")})})});
//# sourceMappingURL=index.js.map
