import{S as u,a as c}from"./assets/vendor-L0i5n3rU.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const l=new u(".swiper",{navigation:{nextEl:".swiper-button-n",prevEl:".swiper-button-p"},pagination:{el:".swiper-pagination"},spaceBetween:10,reachBeginning:".swiper-button-p",reachEnd:".swiper-button-n",keyboard:{enabled:!0,onlyInViewport:!0},autoHeight:!0,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}}});l.on("reachEnd",function(){let e=document.querySelector(".swiper-button-n");e.style.border="1px solid #e4e5e6",e.style.pointerEvents="none";let o=document.querySelector(".btn-icon-n");o.style.stroke="#e4e5e6"});l.on("reachBeginning",function(){let e=document.querySelector(".swiper-button-p");e.style.border="1px solid #e4e5e6",e.style.pointerEvents="none";let o=document.querySelector(".btn-icon-p");o.style.stroke="#e4e5e6"});l.on("fromEdge",function(){let e=document.querySelector(".swiper-button-n");e.style.display="flex",e.style.border="1px solid #292929",e.style.pointerEvents="auto";let o=document.querySelector(".btn-icon-n");o.style.stroke="#292929";let n=document.querySelector(".swiper-button-p");n.style.display="flex",n.style.border="1px solid #292929",n.style.pointerEvents="auto";let s=document.querySelector(".btn-icon-p");s.style.stroke="#292929"});const p=document.querySelector(".review-list");fetch("https://portfolio-js.b.goit.study/api/reviews").then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{const o=e.map(n=>`
  <li class="review-list-order swiper-slide" id = "id_${n._id}">
  <div class="list-order-container">          
  <p class="review-list-text">${n.review}</p>
            <div class="review-list-box">
            <img class="review-list-img" src="${n.avatar_url}" alt="${n.author}">
                <p class="review-list-header">${n.author}</p>
                </div>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o)}).catch(e=>console.log(e));document.getElementById("contactForm").addEventListener("submit",async function(e){var t,r;e.preventDefault(),c.defaults.baseURL="https://portfolio-js.b.goit.study/api";const o=e.target,n=o.email.value.trim(),s=o.message.value.trim();if(!n||!s){a("Please fill in all the fields.");return}try{const i=await c.post("/requests",{email:n,message:s})}catch(i){console.error("Помилка:",i);const d=((r=(t=i.response)==null?void 0:t.data)==null?void 0:r.message)||"An unexpected error occurred. Please try again.";a(d)}});function a(e){alert(e)}document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".load-more"),o=document.querySelectorAll(".project-item[hidden]"),n=document.querySelector(".project-item:not([hidden])");let s=0;const t=3;e.addEventListener("click",()=>{for(let r=s;r<s+t&&r<o.length;r++)o[r].removeAttribute("hidden");if(s+=t,n){const r=n.getBoundingClientRect().height;window.scrollBy({left:0,top:r,behavior:"smooth"})}e.blur(),s>=o.length&&(e.style.display="none")})});
//# sourceMappingURL=index.js.map
